trigger:
- master
- features/*

jobs:
#################################################
- job: windows
#################################################
  displayName: windows
  pool:
    vmImage: vs2017-win2016

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 5
  - powershell: |
      & "$(build.sourcesDirectory)/res/UseNode5.ps1"
    displayName: (azure-pipelines-task-lib) use node 5.10.1

  # build/test
  - script: |
      chcp 437
      node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # use node 6
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: |
      chcp 437
      node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node

  ################################################################################
  # VstsTaskSdk
  ################################################################################

  # npm install
  - task: Npm@1
    displayName: (VstsTaskSdk) npm install
    inputs:
      command: install
      workingDir: powershell

  # npm test
  - script: npm test
    displayName: (VstsTaskSdk) npm test
    workingDirectory: powershell

#################################################
- job: linux
#################################################
  displayName: Linux
  pool:
    vmImage: ubuntu-16.04

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 5
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 5.10.1
    inputs:
      versionSpec: "5.10.1"
      
  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # use node 6
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node

#################################################
- job: macOS
#################################################
  displayName: macOS
  pool:
    vmImage: macOS-10.13

  steps:
  ################################################################################
  # azure-pipelines-task-lib
  ################################################################################
  
  # npm install
  - task: Npm@1
    displayName: (azure-pipelines-task-lib) npm install
    inputs:
      command: install
      workingDir: node

  # use node 5
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 5.10.1
    inputs:
      versionSpec: "5.10.1"
      
  # build/test
  - script: node make.js test
    workingDirectory: node
    displayName: (azure-pipelines-task-lib) node make.js test  

  # use node 6
  - task: NodeTool@0
    displayName: (azure-pipelines-task-lib) use node 6.10.3
    inputs:
      versionSpec: "6.10.3"

  # build/test
  - script: node make.js test
    displayName: (azure-pipelines-task-lib) node make.js test
    workingDirectory: node
